Repository cuenca-mx/speid, pull requests merged in 2020-06, with the labels that each got.

#140 Se retiene transacción de entrada por cuenta ordenante
  env.template
  speid/helpers/transaction_helper.py
  tests/views/conftest.py
  tests/views/test_general.py
Labels: help wanted

#142 FIx task process_outgoing_transactions
  speid/tasks/transactions.py
Labels: bug

#157 Fix tests
  .codecov.yml
  .github/workflows/test.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  env.template
  requirements.txt
  speid/__init__.py
  speid/commands/__init__.py
  speid/commands/docker.py
  speid/commands/spei.py
  speid/helpers/callback_helper.py
  speid/helpers/transaction_helper.py
  speid/models/__init__.py
  speid/models/account.py
  speid/models/base.py
  speid/models/helpers.py
  speid/models/requests.py
  speid/models/transaction.py
  speid/types.py
  speid/utils.py
  speid/views.py
  tests/commands/cassettes/test_re_execute_transactions.yaml
  tests/commands/test_spei.py
  tests/conftest.py
  tests/helpers/test_callback_helper.py
  tests/models/test_helpers.py
  tests/models/test_requests.py
  tests/tasks/cassettes/test_resend_not_success_order.yaml
  tests/tasks/test_accounts.py
  tests/tasks/test_orders.py
  tests/tasks/test_transactions.py
  tests/test_init.py
  tests/views/test_general.py
Labels: enhancement
